improve test
Christianlopez4/protractor-workshop-20201-v2 pull request #2
Opened 2020-09-28 23:33 UTC by Christianlopez4

2020-09-28 23:37 UTC, renardete approved these changes

2020-09-28 23:37 UTC, renardete commented on test/google.spec.ts
> +      expect(browser.getTitle()).toEqual("Google");
set it as a variable in case it could change in the future.

2020-09-28 23:37 UTC, renardete commented on test/google.spec.ts
> +      browser.get("http://www.google.com");
Set it as a variable, and give it a meaningfull name

2020-09-28 23:37 UTC, renardete requested changes
update PR

2020-09-29 00:00 UTC, Christianlopez4 commented on test/google.spec.ts
> +      browser.get("http://www.google.com");
I already set the domain as a variable

2020-09-29 00:55 UTC, renardete approved these changes

2020-09-29 00:57 UTC, merged